kind: Secret
apiVersion: v1
metadata:
  name: amq-app-secret
  annotations:
    description: >-
      Default secret file containing A-MQ 'broker.ks' and 'broker.ts'.  The
      password for the keystore is 'password' and the password for the
      truststore is 'password'
data:
  broker.ks: >-
    /=====
  broker.ts: >-
    /=====
type: Opaque
